name: Verify

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run linters
      run: ./gradlew lint ktlintCheck --continue
    - name: Upload lib reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: lib-reports
        path: lib/build/reports
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run JVM tests
      run: ./gradlew test
    - name: Upload lib reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: lib-reports
        path: lib/build/reports
